version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: app
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db
    networks:
      - mynetwork
    volumes:
      - ./:/usr/app

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    container_name: db
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - mynetwork

volumes:
  postgres-data:

networks:
  mynetwork:
    driver: bridge